import os
import streamlit as st
from transformers import BlipProcessor, BlipForConditionalGeneration, pipeline
from PIL import Image
import torch

# === Add Galaxy Themed Background ===
galaxy_bg = """
<style>
body {
    background: radial-gradient(ellipse at bottom, #1b2735 0%, #090a0f 100%);
    color: #fff;
}
.stApp {
    background: radial-gradient(ellipse at bottom, #3a1c71 0%, #1b2735 100%);
    min-height: 100vh;
}
.stApp::before {
    content: "";
    position: fixed;
    top: 0; left: 0; right: 0; bottom: 0;
    z-index: -1;
    background: transparent url('https://raw.githubusercontent.com/streamlit/example-data/master/galaxy-stars.png') repeat;
    opacity: 0.5;
    pointer-events: none;
}
</style>
"""
st.markdown(galaxy_bg, unsafe_allow_html=True)

# === Step 1: Set up Hugging Face Token ===
os.environ["HF_TOKEN"] = "HF_TOKEN"  # Demo token for workshop

st.title("🖼️ Image Captioning & Cooking QA Demo")

# === Step 2: Image Upload Box ===
uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])
if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Uploaded Image", use_column_width=True)

    # === Step 3: Load BLIP model and generate caption ===
    with st.spinner("Generating caption..."):
        processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
        model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")
        inputs = processor(images=image, return_tensors="pt")
        with torch.no_grad():
            output = model.generate(**inputs)
            caption = processor.decode(output[0], skip_special_tokens=True)

    st.markdown("### 📝 Caption generated by BLIP model:")
    st.write(caption)

    # === Step 4: Use QA model to extract ingredients and steps ===
    qa_pipeline = pipeline("question-answering", model="deepset/roberta-base-squad2")

    questions = [
        "What are the ingredients?",
        "What are the cooking actions?"
    ]

    st.markdown("### 🔍 Ask about the caption:")

    for q in questions:
        if st.button(f"Ask: {q}"):
            with st.spinner(f"Answering: {q}"):
                result = qa_pipeline(question=q, context=caption)
                st.success(f"**Q:** {q}\n\n**A:** {result['answer']}")
else:
    st.info("Please upload an image to get started.")